void CWE775_Missing_Release_of_File_Descriptor_or_Handle__w32CreateFile_no_close_52b_badSink(HANDLE data)
{
    CWE775_Missing_Release_of_File_Descriptor_or_Handle__w32CreateFile_no_close_52c_badSink(data);
}